export enum ProductName {
    NALAR_SELF_DIAGNOSE = 'Nalar Self Diagnose',
    MEDICAL_PRESCRIPTION = 'Medical Prescription',
    OFFLINE_CONSULTATION = 'Offline Consultation General Practicioner',
    LIFE_INSURANCE = 'Life Insurance',
    IN_PATIENT_CASH_PLAN = 'In-patient Cash Plan',
}

export enum PackageName {
    BASIC = 'basic-plan',
    STANDARD = 'standard-plan',
    PREMIUM = 'premium-plan',
}

export enum BenefitCode {
    TELECONSULTATION = 'TLC',
    ONLINE_DRUGS = 'ODG',
    AREA_OF_COVER = 'AOC',
    DIAGNOSTIC = 'DNT',
    EMERGENCY_OUTPATIENT = 'EMR',
    DRUGS = 'DGS',
    F2F_GP = 'FGP',
    F2F_SP = 'FSP',
    ANNUAL_LIMIT = 'ANN',
    HOSPITALIZATION = 'HOC',
    ROOM_AND_BOARD = 'RBO',
    OPERATING_THEATRE = 'OTC',
    NURSING = 'NDD',
    SURGEON_AND_ANAESTHETIST = 'SAC',
    INTENSIVE_CARE_UNIT = 'ICC',
    IMAGING = 'CXT',
    SURGERY = 'SGS',
    MISCELLANEOUS = 'MIS',
    PRE_AND_POST_HOSPITALIZATION = 'PPH',
    PRE_HOSPITALIZATION = 'PRH',
    POST_HOSPITALIZATION = 'POH',
    THERAPY = 'PTT',
    MINOR_SURGERY = 'SGM',
    AMBULANCE = 'AMB',
    CANCER_KIDNEY_DIALYSIS = 'CKD',
    CASH_BENEFIT = 'COV',
    SUB_ANNUAL_LIMIT = 'SNN',
    NURSE_AT_HOME = 'HNN',
    DENTAL_CARE = 'DEN',
    EYE_CARE = 'EYE',
    VACCINATION = 'VAK',
    HEALTH_CHECK = 'MCU',
    LABOUR_AND_DELIVERY = 'DLV',
    PRE_AND_POST_DELIVERY = 'PPD',
    NORMAL_DELIVERY = 'CDB',
    CHILDBIRTH_COMPLICATION = 'CBY',
    NEWBORN_BABY = 'BBY',
    REY_CARD = 'RCD',
    SHORT_PERIOD = 'SPR',
    MEDIUM_PERIOD = 'MPR',
    LONG_PERIOD = 'LPR',
    INPATIENT_EXCESS = 'IPE',
    INPATIENT_ALLOWANCE = 'IAL',
    ONLINE_NUTRITIONIST = 'NUT',
}

export enum BenefitCheckState {
    ERROR= 'error',
    OK= 'ok'
}

export const PLAN_TYPE = {
    COMPLETE_CARE: 'inpatient-complete',
    CRITICAL_CARE: 'inpatient-critical',
    ACCIDENT_CARE: 'inpatient-accident',
    OUTPATIENT_CARE: 'outpatient',
    INPATIENT_ENTERPRISE_CARE: 'inpatient-enterprise',
    OUTPATIENT_ENTERPRISE_CARE: 'outpatient-enterprise',
    DOW_ENTERPRISE_CARE: 'dow-enterprise',
    DOW_ENTERPRISE_DENTAL: 'dow-enterprise-dental',
    DOW_ENTERPRISE_WELLNESS: 'dow-enterprise-wellness',
    DOW_ENTERPRISE_OPTIC: 'dow-enterprise-optical',
    MATERNITY_ENTERPRISE_CARE: 'maternity-enterprise',
    MEMBERSHIP: 'membership',
    ONE_TIME_PRODUCT: 'onetime',
    INPATIENT_ALLOWANCE_WORLDWIDE: 'inpatient-allowance-worldwide',
    INPATIENT_ALLOWANCE_INDONESIA: 'inpatient-allowance-indonesia',
    MEMBERSHIP_NUTRITIONIST: 'membership-nutritionist',
};
